### ISSUE TITLE
In application detail view, denote when an application has been loaded from a plugin

### ISSUE THREAD

**Issue by phildougherty** [growbrosops/containership.plugin.navigator#16]
We need to denote when an application has been loaded by a plugin via something visual in the application detail view. This could be something in the tags like "plugin:service-discovery".

**Comment by normanjoyner** [comment]
:+1: I like this idea. We may need to whitelist a key such as `metadata` where we can store information pertaining to the application, without having it affect deployments. A regular tag will force the application to run on a matching host with the same tag.  How do you feel about something like `metadata.plugin=service-discovery` or `metadata.launched_by=containership.plugin.service-discovery`?

**Comment by phildougherty** [comment]
Ok yeah the tag point makes total sense. In that case I think I like metadata.plugin=service-discovery a little better.

**Comment by normanjoyner** [comment]
This was merged and will be integrated in the next release of `containership.scheduler`. These tags will automatically be denoted on an application page under the 'tags' section.
